name: "Minikube wf"
on:
    push: 
      branches: 
        - develop
    pull_request:
      branches:
        - main
env:
    access_key: ${{vars.AWS_CLIENT_ID}}
    region: ${{vars.REGION}}
    repo: ${{vars.ECR_REPO}}
    client_secret: ${{secrets.AWS_SECRET}}
    ecr_reg: "${{secrets.AWS_ID}}.dkr.ecr.eu-south-2.amazonaws.com"

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Docker login"
        uses: docker/login-action@v3
        with:
          username: ${{env.access_key}}
          password: ${{env.client_secret}}
          registry: ${{env.ecr_reg}}
      - name: "Build and push to ECR"
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "${{env.ecr_reg}}/actions/backend"


